In [1]:
import numpy as np

In [29]:
def minkowski(x1,y1,p):
    for idx in range(len(x1)):
        return abs(((x1[idx] - y1[idx])**p)**abs(-p))
minkowski(x1 = np.array(range(0,5)),y1 = np.array(range(6,11)), p = 2)     
    

1296

In [5]:
def min

array([0, 1, 2, 3, 4])

In [31]:
m = np.arange(40).reshape(10,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [40]:
m[0:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23],
       [24, 26, 27],
       [28, 30, 31],
       [32, 34, 35],
       [36, 38, 39]])

In [41]:
m[-1,-1]

39

In [65]:
a = np.arange(0,4).reshape(2,2)
b = np.arange(4,8).reshape(2,2)
mul = a * b
mul

array([[ 0,  5],
       [12, 21]])

In [55]:
nor = np.sum(mul[1,: ])
nor
mul[1,:]/(nor)

array([0.45614035, 0.54385965])

In [68]:
def func(a1,a2):
    mul = a1 * a2
    l_row = mul[1,: ]
    nor = np.sum(mul[1,:])
    print(l_row/nor)
func(a1 = np.arange(0,4).reshape(2,2), a2 = np.arange(4,8).reshape(2,2))    

[0.36363636 0.63636364]


In [69]:
def minkowski(x1,y1,p):
    for idx in range(len(x1)):
        return abs(((x1[idx] - y1[idx])**p)**abs(-p))
minkowski(x1 = np.array(range(0,5)),y1 = np.array(range(6,11)), p = 2)     
    

1296

In [96]:
x = np.arange(85,101)       
y = np.arange(15,31)
x_even = x[x%2 == 0]
x_even
y_even = y[y%2 == 0]
y_even


array([16, 18, 20, 22, 24, 26, 28, 30])

In [126]:
def func(a1,a2):
    mul = a1 * a2
    a = mul[:,: ]
    nor = np.sum(mul[:,:])
    print(a/nor)
func(a1 = np.arange(0,4).reshape(2,2), a2 = np.arange(4,8).reshape(2,2))    

[[0.         0.13157895]
 [0.31578947 0.55263158]]


In [127]:
a[1,:] / nor

array([0.03508772, 0.05263158])

In [131]:
a

array([[0, 1],
       [2, 3]])

In [132]:
mul 

array([[ 0,  5],
       [12, 21]])

In [136]:
nor1 = mul[1, 0:2]
nor1

array([12, 21])

In [139]:
s = np.sum(nor1)

In [142]:
v2 = nor1/s

In [141]:
mul

array([[ 0,  5],
       [12, 21]])

In [144]:
v1 = mul[0,:]
v1

array([0, 5])

In [149]:
v_stack = np.vstack((v1,v2))
v_stack

array([[0.        , 5.        ],
       [0.36363636, 0.63636364]])